FROM golang:1.16 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN make build-server

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/builds/pando-server .
COPY --from=builder /app/assets .

EXPOSE 7778

ENTRYPOINT ["/app/pando-server"]
