FROM golang:1.16 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN make build-worker

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/builds/pando-worker /bin/

EXPOSE 7777

ENTRYPOINT ["/bin/pando-worker"]
