// Code generated by "stringer --type FlipPhase --trimprefix FlipPhase"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlipPhaseTend-1]
	_ = x[FlipPhaseDent-2]
	_ = x[FlipPhaseBid-3]
	_ = x[FlipPhaseDeal-4]
}

const _FlipPhase_name = "TendDentBidDeal"

var _FlipPhase_index = [...]uint8{0, 4, 8, 11, 15}

func (i FlipPhase) String() string {
	i -= 1
	if i < 0 || i >= FlipPhase(len(_FlipPhase_index)-1) {
		return "FlipPhase(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FlipPhase_name[_FlipPhase_index[i]:_FlipPhase_index[i+1]]
}
