// Code generated by "stringer -type ProposalAction -trimprefix ProposalAction"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProposalActionVote-1]
	_ = x[ProposalActionWithdraw-2]
	_ = x[ProposalActionSetProperty-3]
}

const _ProposalAction_name = "VoteWithdrawSetProperty"

var _ProposalAction_index = [...]uint8{0, 4, 12, 23}

func (i ProposalAction) String() string {
	i -= 1
	if i < 0 || i >= ProposalAction(len(_ProposalAction_index)-1) {
		return "ProposalAction(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ProposalAction_name[_ProposalAction_index[i]:_ProposalAction_index[i+1]]
}
