// Code generated by "stringer -type TransactionStatus -trimprefix TransactionStatus"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TransactionStatusPending-0]
	_ = x[TransactionStatusAbort-1]
	_ = x[TransactionStatusOk-2]
}

const _TransactionStatus_name = "PendingAbortOk"

var _TransactionStatus_index = [...]uint8{0, 7, 12, 14}

func (i TransactionStatus) String() string {
	if i < 0 || i >= TransactionStatus(len(_TransactionStatus_index)-1) {
		return "TransactionStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransactionStatus_name[_TransactionStatus_index[i]:_TransactionStatus_index[i+1]]
}
